---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


```{r, echo = FALSE}
setwd("C:/Users/kristoffer.peyron/Dropbox/Coursera/Data Science Specialization/5. Reproducible Research/week 2/RepData_PeerAssessment1")

knitr::opts_chunk$set(message = FALSE, warning = FALSE)


```


## Loading and preprocessing the data

```{r}

if(!file.exists("activity.csv")){
        unzip("activity.zip")
}

data <- read.csv("activity.csv")

require(dplyr)

stepsByDate <- data %>% group_by(date) %>% 
        summarise(steps = sum(steps))

avgStepsByInterval <- data %>% group_by(interval) %>% summarise(avgSteps = mean(steps, na.rm = TRUE))


```


## What is mean total number of steps taken per day?
```{r}
require(ggplot2)
require(ggthemes)
ggplot(stepsByDate, aes(steps)) + geom_histogram(fill = '#334385', color = 'black', binwidth = 500) + theme_economist() + labs(title = 'Histogram over Steps') + theme(plot.title = element_text(hjust = 0.5))

mean <- mean(stepsByDate$steps, na.rm = TRUE)
median <- median(stepsByDate$steps, na.rm = TRUE)

```
- Mean: `r mean`
- Median: `r median`


## What is the average daily activity pattern?
```{r}
ggplot(avgStepsByInterval, aes(interval, avgSteps)) + geom_line(color ='#33877D') + theme_economist()

maxInterval <- avgStepsByInterval$interval[which.max(avgStepsByInterval$avgSteps)]

```
- Interval which has the maximum of average steps: `r maxInterval`


## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
